# Vesty App - Production Docker Compose (HTTP Only - Initial Setup)
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vesty-app-prod
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Nginx reverse proxy (HTTP only for now)
  nginx:
    image: nginx:alpine
    container_name: vesty-nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always
